# Generated by Django 4.0.4 on 2022-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
